#!/usr/bin/perl
########################################################
# LiteSpeed webserver : number of hits 
# Written by Alex S Grebenschikov (www.poralix.com)
# Created at: Mon Apr  8 10:57:04 CEST 2019
########################################################
if ( $ARGV[0] eq 'autoconf' ) {
   if ( -e '/dev/shm/status/.rtreport' ) {
      print "yes\n";
      exit;
   } else {
      print "no\n";
      exit 1;
   }
}

if ( $ARGV[0] eq 'config' ) {
   print "graph_title Litespeed : hits\n";
   print "graph_args --base 1000 -l 0\n";
   print "graph_scale no\n";
   print "graph_vlabel hits\n";
   print "graph_category litespeed\n";
   print "hits_total.label Total Static Hits\n";
   print "hits_total.draw AREA\n";
   print "cache_public.label Total Public Cache Hits\n";
   print "cache_public.draw LINE1\n";
   print "cache_private.label Total Private Cache Hits\n";
   print "cache_private.draw LINE1\n";
   exit 0;
}

if ( ! -e '/dev/shm/status/.rtreport' ) {
   print "hits_total.value 0\n";
   print "cache_public.value 0\n";
   print "cache_private.value 0\n";
   exit 0;
}

@stats = `ls -a /dev/shm/status/.rtreport*`;
foreach $rep ( @stats ) {
   open IN, "<$rep";
   while ( <IN> ) {
      # TOTAL_PUB_CACHE_HITS: 3827
      # TOTAL_PRIVATE_CACHE_HITS: 8144
      # TOTAL_STATIC_HITS: 25827
      if ( /TOTAL_PUB_CACHE_HITS: (\d+), PRIVATE_CACHE_HITS_PER_SEC: ([0-9]*\.?[0-9]+), TOTAL_PRIVATE_CACHE_HITS: (\d+), STATIC_HITS_PER_SEC: ([0-9]*\.?[0-9]+), TOTAL_STATIC_HITS: (\d+)/ ) {
         $hits_total += $1;
         $cache_public += $3;
         $cache_private += $5;
         last;
      }
   }
   close IN;
}
print "hits_total.value $hits_total\ncache_public.value $cache_public\ncache_private.value $cache_private\n";
exit;
